[project]
name = "qwen-awesome"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.7.9",
    "dotenv>=0.9.9",
    "logfire>=4.2.0",
    "openai>=1.99.6",
    "pydantic-ai>=0.6.2",
    "rizaio>=0.12.0",
]
